# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fib = lambda{|a,b| [b, a+b] }

sum = 0
pair = [1,2]

while pair[1] < 4000000
  sum += pair[1] if pair[1]%2==0
  pair = fib.call(*pair)
end

puts sum